version: 2

defaults: &defaults
  parallelism: 1
  working_directory: ~/zunder
  docker:
    - image: cypress/base:8
      environment:
        TERM: xterm
        npm_config_loglevel: warn

jobs:
  install-and-cache-deps:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: zunder-{{ checksum circle.yml }}-{{ .Branch }}-{{ checksum "package-lock.json" }}
          key: zunder-{{ checksum circle.yml }}-{{ .Branch }}
          key: zunder-{{ checksum circle.yml }}-
      - run: npm ci
      # run verify and then save cache. Then verified status is cached
      - run: npm run cypress:verify
      - save_cache:
          key: zunder-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm
            - ~/.cache
      - persist_to_workspace:
          root: ~/
          paths:
            - zunder/node_modules
            - zunder/test/projects/node_modules

  lint:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: zunder-{{ .Branch }}-{{ checksum "package-lock.json" }}
          key: zunder-{{ .Branch }}
          key: zunder-
      - run: echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' >> .npmrc
      - run: npm ci
      - run: cd test/projects && npm ci
      - run: npm run lint
      - persist_to_workspace:
          root: ~/
          paths:
            - zunder/node_modules
            - zunder/test/projects/node_modules

  test:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/
      - run: npm test -- --record
      - store_artifacts:
          path: npm-debug.log

workflows:
  version: 2
  "lint & test":
    jobs:
      - install-and-cache-deps
      - lint
      - test
